/****************************************************
 *
 * ****     ***     ****    *   *    *****    *****
 * *  *    *   *   *        ****     ***        *
 * *   *    ***     ****    *   *    *****      *
 *
 * append_log.h
 * 2024-04-23 15:28:24
 * Generated by rocket framework rocket_generator.py
 * File will not generate while exist
 * Allow editing
****************************************************/

#ifndef RAFT_SERVER_INTERFACE_APPEND_LOG_H
#define RAFT_SERVER_INTERFACE_APPEND_LOG_H 

#include <rocket/net/rpc/rpc_closure.h>
#include "../pb/raft_server.pb.h"
#include "interface.h"


namespace raft_server {

/*
 * Rpc Interface Class
 * Alloc one object every time RPC call begin, and destroy this object while RPC call end
*/

class AppendLogInterface : public Interface {
 public:

  AppendLogInterface(const ::appendLogRequest* request, ::appendLogResponse* response, 
    rocket::RpcClosure* done, rocket::RpcController* controller);

  ~AppendLogInterface();

 public:
  // core business deal method
  virtual void run() override;

  // set error code and error into to response message
  virtual void setError(int code, const std::string& err_info) override;

 private:
  const ::appendLogRequest* m_request {NULL};       // request object fron client

  ::appendLogResponse* m_response {NULL};           // response object that reply to client

};


}


#endif