/****************************************************
 *
 * ****     ***     ****    *   *    *****    *****
 * *  *    *   *   *        ****     ***        *
 * *   *    ***     ****    *   *    *****      *
 *
 * call_vote.cc
 * 2024-04-23 15:28:24
 * Generated by rocket framework rocket_generator.py
 * File will not generate while exist
 * Allow editing
****************************************************/


#include <rocket/common/log.h>
#include "call_vote.h"
#include "../interface/interface.h"
#include "../pb/raft_server.pb.h"

namespace raft_server {

CallVoteInterface::CallVoteInterface(const ::callVoteRequest* request, ::callVoteResponse* response, 
    rocket::RpcClosure* done, rocket::RpcController* controller, bool log_checked, int term, int voted_for)
  : Interface(dynamic_cast<const google::protobuf::Message*>(request), dynamic_cast<google::protobuf::Message*>(response), done, controller),
    m_request(request), m_response(response), m_log_checked(log_checked), m_term(term), 
    m_voted_for(voted_for) {
  APPINFOLOG("In|request:{%s}", request->ShortDebugString().c_str());
}

CallVoteInterface::~CallVoteInterface() {
  APPINFOLOG("Out|response:{%s}", m_response->ShortDebugString().c_str());
}

void CallVoteInterface::run() {

  //
  // Run your business logic at here
  // 
  if(m_request->term() < m_response->term()) {
    m_response->set_vote_granted(false);
  } else {
    m_response->set_term(m_request->term());
    
  }

  m_response->set_ret_code(0);
  m_response->set_res_info("OK");

}

void CallVoteInterface::setError(int code, const std::string& err_info) {
  m_response->set_ret_code(code);
  m_response->set_res_info(err_info);
}

}