/****************************************************
 *
 * ****     ***     ****    *   *    *****    *****
 * *  *    *   *   *        ****     ***        *
 * *   *    ***     ****    *   *    *****      *
 *
 * raft_server.h
 * 2024-04-23 15:28:24
 * Generated by rocket framework rocket_generator.py
 * Do not edit !!!
****************************************************/


#ifndef RAFT_SERVER_SERVICE_RAFT_SERVER_H 
#define RAFT_SERVER_SERVICE_RAFT_SERVER_H

#include <google/protobuf/service.h>
#include "../pb/raft_server.pb.h"

namespace raft_server {

class RaftServerImpl : public RaftServer {

 public:

  RaftServerImpl() = default;

  ~RaftServerImpl() = default;

  // override from RaftServer
  virtual void call_vote(::google::protobuf::RpcController* controller,
                       const ::callVoteRequest* request,
                       ::callVoteResponse* response,
                       ::google::protobuf::Closure* done, bool log_checked, int term, int voted_for);

  // override from RaftServer
  virtual void append_log(::google::protobuf::RpcController* controller,
                       const ::appendLogRequest* request,
                       ::appendLogResponse* response,
                       ::google::protobuf::Closure* done);

  

};

}


#endif