/****************************************************
 *
 * ****     ***     ****    *   *    *****    *****
 * *  *    *   *   *        ****     ***        *
 * *   *    ***     ****    *   *    *****      *
 *
 * raft_server.cc
 * 2024-04-23 15:28:24
 * Generated by rocket framework rocket_generator.py
 * Do not edit !!!
****************************************************/


#include <google/protobuf/service.h>
#include <exception>
#include <rocket/common/log.h>
#include "../pb/raft_server.pb.h"
#include "raft_server.h"
#include "../comm/business_exception.h"
#include "../interface/call_vote.h"
#include "../interface/append_log.h"


#define CALL_VOTE_RPC_INTERFACE(Type)                                                                                               \
  {                                                                                                                                 \
    rocket::RpcClosure* clo = dynamic_cast<rocket::RpcClosure*>(done);                                                              \
    rocket::RpcController* con = dynamic_cast<rocket::RpcController*>(controller);                                                  \
    std::shared_ptr<Type> impl = std::make_shared<Type>(request, response, clo, con, log_checked, term, voted_for);                 \
    rocket::RunTime::GetRunTime()->m_rpc_interface = std::dynamic_pointer_cast<rocket::RpcInterface>(impl).get();                   \
    response->set_ret_code(0);                                                                                                      \
    response->set_res_info("OK");                                                                                                   \
    try {                                                                                                                           \
      impl->run();                                                                                                                  \
    } catch (BusinessException& e) {                                                                                                \
      APPDEBUGLOG("business exception");                                                                                            \
      response->set_ret_code(e.errorCode());                                                                                        \
      response->set_res_info(e.errorInfo());                                                                                        \
    } catch (rocket::RocketException& e) {                                                                                          \
      APPDEBUGLOG("RocketException");                                                                                               \
      response->set_ret_code(-1);                                                                                                   \
      response->set_res_info("Unknown RocketException");                                                                            \
    } catch (std::exception& e) {                                                                                                   \
      APPDEBUGLOG("std::exception");                                                                                                \
      response->set_ret_code(-1);                                                                                                   \
      response->set_res_info("Unknown std::exception");                                                                             \
    } catch (...) {                                                                                                                 \
      APPDEBUGLOG("... exception");                                                                                                 \
      response->set_ret_code(-1);                                                                                                   \
      response->set_res_info("Unknown exception");                                                                                  \
    }                                                                                                                               \
  }                                                                                                                                 \

#define CALL_RPC_INTERFACE(Type)                                                                                                    \
  {                                                                                                                                 \
    rocket::RpcClosure* clo = dynamic_cast<rocket::RpcClosure*>(done);                                                              \
    rocket::RpcController* con = dynamic_cast<rocket::RpcController*>(controller);                                                  \
    std::shared_ptr<Type> impl = std::make_shared<Type>(request, response, clo, con);                                               \
    rocket::RunTime::GetRunTime()->m_rpc_interface = std::dynamic_pointer_cast<rocket::RpcInterface>(impl).get();                   \
    response->set_ret_code(0);                                                                                                      \
    response->set_res_info("OK");                                                                                                   \
    try {                                                                                                                           \
      impl->run();                                                                                                                  \
    } catch (BusinessException& e) {                                                                                                \
      APPDEBUGLOG("business exception");                                                                                            \
      response->set_ret_code(e.errorCode());                                                                                        \
      response->set_res_info(e.errorInfo());                                                                                        \
    } catch (rocket::RocketException& e) {                                                                                          \
      APPDEBUGLOG("RocketException");                                                                                               \
      response->set_ret_code(-1);                                                                                                   \
      response->set_res_info("Unknown RocketException");                                                                            \
    } catch (std::exception& e) {                                                                                                   \
      APPDEBUGLOG("std::exception");                                                                                                \
      response->set_ret_code(-1);                                                                                                   \
      response->set_res_info("Unknown std::exception");                                                                             \
    } catch (...) {                                                                                                                 \
      APPDEBUGLOG("... exception");                                                                                                 \
      response->set_ret_code(-1);                                                                                                   \
      response->set_res_info("Unknown exception");                                                                                  \
    }                                                                                                                               \
  }                                                                                                                                 \

namespace raft_server {

void RaftServerImpl::call_vote(::google::protobuf::RpcController* controller,
                       const ::callVoteRequest* request,
                       ::callVoteResponse* response,
                       ::google::protobuf::Closure* done, bool log_checked, int term, int voted_for){

  CALL_VOTE_RPC_INTERFACE(CallVoteInterface);
}

void RaftServerImpl::append_log(::google::protobuf::RpcController* controller,
                       const ::appendLogRequest* request,
                       ::appendLogResponse* response,
                       ::google::protobuf::Closure* done){

  CALL_RPC_INTERFACE(AppendLogInterface);
}



}